### ISSUE TITLE
W3C's servers fail when used in Safari with html-validator

### ISSUE THREAD

**Issue by ckortekaas** [zrrrzzt/html-validator#202]
First of all, thanks for your efforts providing this package. It's greatly appreciated!

W3C's server rejects the 'User-Agent' header and return a '[Error] Unhandled Promise Rejection: TypeError: Request header field User-Agent is not allowed by Access-Control-Allow-Headers' message. 

Chrome and other browser seem to lower-case them (Chrome since version 60) and are not affected. Please lowercase the 'User-Agent' string in config.js and this problem should go away.

To replicate, use any web-app that uses this module in Safari (or iOS Safari) with the default settings for header options.

Since the way config.js forces 'User-Agent', just using header options overrides will not solve this in Safari, so will need an explicit lowercasing (or maybe reordering of params in Object.Assign) to resolve this bug.

Due to the problem with compiling imports with webpack and html-validate (now a dependency of 5.1.x) in https://gitlab.com/html-validate/html-validate/-/issues/80, please release a 5.0.x with a patch for this too and it would be greatly appreciated!

Apologies if there is a known workaround for this.

**Comment by zrrrzzt** [comment]
Should be fixed in 5.10.1

Let me know if there still is any problems :-)

**Comment by ckortekaas** [comment]
@zrrrzzt Thanks! But I can't use 5.1.x because it is not compatible with WebPack. Due to https://gitlab.com/html-validate/html-validate/-/issues/80 and https://gitlab.com/html-validate/html-validate/-/issues/79. Is there any chance you could backport this fix to 5.0.x for us WebPack users?

**Comment by zrrrzzt** [comment]
ooops. Was a bit bit too quick here, sorry :-)

So I've solved the `user-agent`problem. The Webpack problem is due to my use of `html-validate` for local validation.

I'll reopen the issue and see what I can do. Do you have a minimal repo with webpack I could look at? If possible I would rather have everything working in the newest version.

**Comment by ckortekaas** [comment]
That's OK! I'm afraid I don't have a public minimal Webpack repo available for testing right now. It would be great to have everything working in the newest version but by the look of the gitlab issues in html-validate, I doubt html-validator can work with Webpack if it keeps depending on html-validate, at least until those issues are completed. And it looks like html-validate is looking for support to solve them, so it might be quite some time. I would lend my support, but I'm more of a backend developer myself :) If those config.js changes could be backported to a 5.0.x, for now, that would help anyone trying to build this with Webpack like myself.

**Comment by zrrrzzt** [comment]
I've released a version 5.0.2 on npm to help you out in the meantime

**Comment by ckortekaas** [comment]
@zrrrzzt thanks for persisting with this. This has not fixed the issue because there is still no way NOT to send a user-agent key. The only allowed header by the w3 website is 'Content-Type'. So if you send a User-Agent or user-agent, or anything other than just Content-Type in the headers it will be in violation and Safari will throw the error. If you removed the entire setUserAgent function and the reference to it in Object.assign, it will fix this bug and even let people add a user-agent in if they want to for other validators (but specifying it in a headers option if they need to). Thanks!

**Comment by zrrrzzt** [comment]
Been away for a couple of hours :-)

So, I think `user-agent` is required for the validator and the problem here is that the same headers are used for requesting the page you want to validate. This is not how it should work. I'll look into it a bit later. Changing this behaviour (let custom headers override everything) is technically a breaking change so I must release it as major. Not a problem but it will complicate the backporting if I follow strict semver.

We'll find a way :-)

**Comment by zrrrzzt** [comment]
Anyway, I only use this module serverside myself. So if you could create a minimal example for a webapp it would be of great help to debug.

**Comment by zrrrzzt** [comment]
Hah, got a minimal webapp up and running. Have managed to reproduce the error you have in Firefox and Safari. It seems to be related to preflight and options/cors and not the headers themselves.

**Comment by zrrrzzt** [comment]
As far as I can see the browser sets it's own headers so this is probably related to the way request behaves in the browsers. It tries to do a preflight in Firefox and Safari, but not in Brave or Chrome.
request is deprecated and will be switched out.

**Comment by zrrrzzt** [comment]
Okay [5.0.3](https://www.npmjs.com/package/html-validator/v/5.0.3) is out.

The solution I ended up with is removing the `user-agent` from headers if the environment is a browser. Hope this works out for you :-)
